### PR TITLE
Add caching to exec Kubernetes client

### PR DESCRIPTION
**Pull request by guaraqe**

### CODE REVIEW

**Comment by istathar** [comment]
@guaraqe I've got an internal build of this working, but there are a few merge conflicts between `'auth-plugin'` and `'main'` that will need to be fixed up. I started trying to resolve them, but there are a few things I couldn't quite tell whether they were current or not, so thought best to leave for you to decide.

**Comment by guaraqe** [comment]
The conflicts are with a previous version of this one, this can basically be made the new `master`.

**Comment by istathar** [comment]
@guaraqe are you planning to merge this [or, as you say, force push it to `'master'`]?

**Comment by guaraqe** [comment]
Yes, I will try to open the PR to the main repo.

**Pull request merged**
